name: 'WF - setup runner'
description: 'sets up the java environment on the runner'
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
