name: 'WF - Gradle Build'
description: 'Workflow action to execute a gradle build inside a subdirectory'
inputs:
  path:
    description: 'path in monorepo to software for this run'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/wf-setup
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x test
        build-root-directory: ${{ inputs.path }}
